sudo: required
dist: xenial

addons:
  apt:
    sources:
      - chef-stable-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

branches:
  only:
    - master
    - /^(?i:travis).*$/

services: docker

env:
  matrix:
    - INSTANCE=v7-ubuntu16
    - INSTANCE=v7-ubuntu18
    - INSTANCE=v7-debian9
    - INSTANCE=v7-centos7
    - INSTANCE=v7-centos8
    - INSTANCE=v7-fedora
    - INSTANCE=v7-amazon
    - INSTANCE=v7-amazon2
    - INSTANCE=v6-ubuntu16
    - INSTANCE=v6-ubuntu18
    - INSTANCE=v6-debian9
    - INSTANCE=v6-centos7
    - INSTANCE=v6-centos8
    - INSTANCE=v6-fedora
    - INSTANCE=v6-amazon
    - INSTANCE=v6-amazon2


script:
  - KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version


matrix:
  include:
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept

